/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fr.ufrsciencestech.compteur.view;

import fr.ufrsciencestech.compteur.controler.Controleur;
import java.awt.Dimension;
import java.util.Observable;
import javax.swing.JFrame;
import javax.swing.JTextArea;

/**
 *
 * @author gs252355
 */
public class VueGSwingNew extends javax.swing.JFrame {

    /**
     * Creates new form VueGSwingNew
     */
    public VueGSwingNew() {
        initComponents();
        this.pack();
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(500, 700);
        
    }
    
    public void addControleur(Controleur c){
       this.AddFruit.addActionListener(c);
       this.RemoveLastFruit.addActionListener(c);
       this.ComboFruits.addActionListener(c);
    }
    
    public JTextArea getJtextArea(){
        return this.AfficheInfos;
    }
    
    public int getItemJCombo(){
        return this.ComboFruits.getSelectedIndex();
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        AddFruit = new javax.swing.JButton();
        ComboFruits = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        AfficheInfos = new javax.swing.JTextArea();
        RemoveLastFruit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        AddFruit.setText("+");
        AddFruit.setName("AddFruit"); // NOI18N
        AddFruit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFruitActionPerformed(evt);
            }
        });
        jPanel2.add(AddFruit);

        ComboFruits.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banane", "Cerise", "Macédoine de banane et cerise" }));
        ComboFruits.setName("ComboFruits"); // NOI18N
        jPanel2.add(ComboFruits);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        AfficheInfos.setColumns(20);
        AfficheInfos.setRows(5);
        jScrollPane1.setViewportView(AfficheInfos);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        RemoveLastFruit.setText("-");
        RemoveLastFruit.setMaximumSize(new java.awt.Dimension(10, 10));
        RemoveLastFruit.setMinimumSize(new java.awt.Dimension(10, 10));
        RemoveLastFruit.setName("RemoveLastFruit"); // NOI18N
        jPanel1.add(RemoveLastFruit, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddFruitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFruitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddFruitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueGSwingNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueGSwingNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueGSwingNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueGSwingNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueGSwingNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFruit;
    private javax.swing.JTextArea AfficheInfos;
    private javax.swing.JComboBox<String> ComboFruits;
    private javax.swing.JButton RemoveLastFruit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
